"""Smoke tests for HTML rendering in generate-report.py and generate-dashboard.py.

Calls generate_html / generate_dashboard with minimal data and asserts the
output contains expected JS functions, Mermaid syntax, and CSS braces.
Catches regressions where lint auto-fixes break f-string brace escaping.
"""
import importlib.util
import os
import tempfile

SCRIPTS_DIR = os.path.join(os.path.dirname(__file__), "..", "scripts")


def _load_module(filename, modname):
    path = os.path.join(SCRIPTS_DIR, filename)
    spec = importlib.util.spec_from_file_location(modname, path)
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod


report = _load_module("generate-report.py", "generate_report")
dashboard = _load_module("generate-dashboard.py", "generate_dashboard")


def _minimal_task():
    return {
        "meta": {
            "title": "Test strategy",
            "source_rfe": "RHAIRFE-0001",
            "priority": "Major",
            "status": "New",
        },
        "body": "RFE body\n\n## Strategy (AI Generated by Agentic SDLC Pipeline)\n\nStrategy text",
    }


def _minimal_review():
    return {
        "meta": {
            "recommendation": "approve",
            "needs_attention": False,
            "reviewers": {
                "feasibility": "pass",
                "testability": "pass",
                "scope": "pass",
                "architecture": "pass",
            },
            "scores": {
                "feasibility": 2,
                "testability": 2,
                "scope": 2,
                "architecture": 2,
                "total": 8,
            },
        },
        "body": "Review body text",
    }


class TestReportHtmlRendering:
    def _render(self):
        tasks = {"RHAISTRAT-1": _minimal_task()}
        reviews = {"RHAISTRAT-1": _minimal_review()}
        with tempfile.NamedTemporaryFile(suffix=".html", delete=False) as f:
            out = f.name
        try:
            report.generate_html(
                tasks, reviews,
                review_comments={},
                skipped=[],
                pending_review=[],
                config={},
                output_path=out,
            )
            with open(out) as f:
                return f.read()
        finally:
            os.unlink(out)

    def test_js_function_braces(self):
        html = self._render()
        assert "function switchPage(page) {" in html
        assert "function toggleDetail(i) {" in html
        assert "function switchTab(i, tab) {" in html
        assert "function zoomDiagram(factor) {" in html
        assert "function resetDiagram() {" in html

    def test_js_block_braces(self):
        html = self._render()
        assert "if (page === 'pipeline' && !mermaidRendered) {" in html
        assert "isDragging = false; });" in html

    def test_mermaid_diamond_nodes(self):
        html = self._render()
        assert "GATE{{Pipeline label gate" in html
        assert "EG{{" in html
        assert "FG{{" in html
        assert "RG{{" in html
        assert "Q{{" in html

    def test_mermaid_decision_nodes(self):
        html = self._render()
        assert 'PA{"AI Strategy HOW' in html

    def test_mermaid_subgraphs(self):
        html = self._render()
        assert 'subgraph P2["Phase 2: Strategy Refinement"]' in html
        assert 'subgraph SC["strategy-create"]' in html

    def test_css_braces(self):
        html = self._render()
        assert "{ cursor: pointer; }" in html

    def test_mermaid_init_braces(self):
        html = self._render()
        assert "mermaid.initialize({" in html
        assert "flowchart: {" in html

    def test_contains_doctype(self):
        html = self._render()
        assert "<!DOCTYPE html>" in html


class TestLoadArtifactsSkipParsing:
    """AISDLC-149: Regression tests for load_artifacts skip entry parsing."""

    def _write_skip_file(self, tmpdir, rows):
        artifacts = os.path.join(tmpdir, "artifacts")
        os.makedirs(os.path.join(artifacts, "strat-tasks"), exist_ok=True)
        skip_path = os.path.join(artifacts, "strat-skipped.md")
        lines = [
            "# Skipped RFEs\n",
            "\n",
            "| RFE Key | Title | Reason | Run |\n",
            "|---------|-------|--------|-----|\n",
        ]
        for row in rows:
            lines.append(f"| {row[0]} | {row[1]} | {row[2]} | {row[3]} |\n")
        with open(skip_path, "w") as f:
            f.writelines(lines)
        return artifacts

    def test_rubric_pass_skip_entry_not_dropped(self):
        reason = (
            "RHAISTRAT-2405 already processed"
            " (label: strat-creator-rubric-pass)"
        )
        with tempfile.TemporaryDirectory() as tmpdir:
            artifacts = self._write_skip_file(tmpdir, [
                ("RHAIRFE-1535", "Notebook image", reason,
                 "batch-jql @ 2026-09-28T16:07Z"),
            ])
            _, _, _, skipped, _ = report.load_artifacts(artifacts)
            assert len(skipped) == 1
            assert skipped[0]["rfe_key"] == "RHAIRFE-1535"

    def test_needs_attention_goes_to_pending_review(self):
        reason = (
            "RHAISTRAT-3000 already processed"
            " (label: strat-creator-needs-attention)"
        )
        with tempfile.TemporaryDirectory() as tmpdir:
            artifacts = self._write_skip_file(tmpdir, [
                ("RHAIRFE-2000", "Some feature", reason,
                 "batch-jql @ 2026-09-28T16:07Z"),
            ])
            _, _, _, skipped, pending_review = (
                report.load_artifacts(artifacts)
            )
            assert len(pending_review) == 1
            assert pending_review[0]["rfe_key"] == "RHAIRFE-2000"
            assert len(skipped) == 0

    def test_non_processed_reason_goes_to_skipped(self):
        reason = "missing labels: rfe-creator-autofix-rubric-pass"
        with tempfile.TemporaryDirectory() as tmpdir:
            artifacts = self._write_skip_file(tmpdir, [
                ("RHAIRFE-3000", "Another feature", reason,
                 "batch-jql @ 2026-09-28T16:07Z"),
            ])
            _, _, _, skipped, pending_review = (
                report.load_artifacts(artifacts)
            )
            assert len(skipped) == 1
            assert len(pending_review) == 0


class TestDashboardHtmlRendering:
    def _render(self):
        run = {
            "run_id": "2026-08-01_test",
            "total": 1,
            "reviewed": 1,
            "approved": 1,
            "approval_rate": 100,
            "delta_approval": None,
            "strategies": [],
        }
        with tempfile.NamedTemporaryFile(suffix=".html", delete=False) as f:
            out = f.name
        try:
            dashboard.generate_dashboard(
                runs=[run],
                exec_summary="Test summary",
                output_path=out,
            )
            with open(out) as f:
                return f.read()
        finally:
            os.unlink(out)

    def test_contains_doctype(self):
        html = self._render()
        assert "<!DOCTYPE html>" in html

    def test_css_body_rule(self):
        html = self._render()
        assert "body {" in html or "body{" in html

    def test_js_function_braces(self):
        html = self._render()
        assert "function " in html
        brace_count = html.count("function ")
        assert brace_count > 0
        assert "{" in html[html.index("function "):]

    def test_chart_js_config(self):
        html = self._render()
        assert "new Chart(" in html
