"""Tests for push_refined_strategies.py — deterministic post-refine push."""
import os
import subprocess
import sys

PROJECT_ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
SCRIPT = os.path.join(PROJECT_ROOT, "scripts", "push_refined_strategies.py")
FRONTMATTER_SCRIPT = os.path.join(PROJECT_ROOT, "scripts", "frontmatter.py")

STRATEGY_HEADING = "## Strategy (AI Generated by Agentic SDLC Pipeline)"


def _env(jira):
    return {
        **os.environ,
        "JIRA_SERVER": jira.url,
        "JIRA_USER": "admin",
        "JIRA_TOKEN": "admin",
    }


def _run(jira, artifacts_dir):
    return subprocess.run(
        [sys.executable, SCRIPT, "--artifacts-dir", str(artifacts_dir)],
        env=_env(jira),
        capture_output=True,
        text=True,
        cwd=PROJECT_ROOT,
    )


def _write_strategy(path, strat_id, source_rfe, status, jira_key=None):
    """Write a strategy file with frontmatter and strategy content."""
    fm_lines = [
        "---",
        f"strat_id: {strat_id}",
        f"title: Test strategy {strat_id}",
        f"source_rfe: {source_rfe}",
        "priority: Major",
        f"status: {status}",
    ]
    if jira_key:
        fm_lines.append(f"jira_key: {jira_key}")
    fm_lines.append("---")
    fm_lines.append("")
    fm_lines.append("## Business Need (from RFE)")
    fm_lines.append("")
    fm_lines.append("Users need this feature.")
    fm_lines.append("")
    fm_lines.append(STRATEGY_HEADING)
    fm_lines.append("")
    fm_lines.append("### Technical Approach")
    fm_lines.append("")
    fm_lines.append(f"Implementation details for {strat_id}.")
    fm_lines.append("")
    path.write_text("\n".join(fm_lines))


class TestPushRefinedStrategies:

    def test_pushes_refined_strategy_with_jira_key(self, jira, art_dir):
        jira.create("RHAISTRAT-2000", "Test push", "## Business Need\n\nContext.")
        strat_dir = art_dir / "artifacts" / "strat-tasks"
        _write_strategy(strat_dir / "RHAISTRAT-2000.md",
                        "RHAISTRAT-2000", "RHAIRFE-100", "Refined",
                        jira_key="RHAISTRAT-2000")

        result = _run(jira, strat_dir)
        assert result.returncode == 0, f"stderr: {result.stderr}"
        assert "[PUSH] RHAISTRAT-2000" in result.stdout
        assert "Pushed 1/" in result.stdout

        issue = jira.get("RHAISTRAT-2000")
        labels = issue["fields"]["labels"]
        assert "strat-creator-auto-refined" in labels

    def test_skips_draft_status(self, jira, art_dir):
        jira.create("RHAISTRAT-2001", "Draft strat", "")
        strat_dir = art_dir / "artifacts" / "strat-tasks"
        _write_strategy(strat_dir / "RHAISTRAT-2001.md",
                        "RHAISTRAT-2001", "RHAIRFE-101", "Draft",
                        jira_key="RHAISTRAT-2001")

        result = _run(jira, strat_dir)
        assert result.returncode == 0
        assert "[SKIP] RHAISTRAT-2001.md" in result.stdout
        assert "Pushed 0/" in result.stdout

    def test_skips_no_jira_key(self, jira, art_dir):
        strat_dir = art_dir / "artifacts" / "strat-tasks"
        _write_strategy(strat_dir / "RHAISTRAT-2002.md",
                        "RHAISTRAT-2002", "RHAIRFE-102", "Refined")

        result = _run(jira, strat_dir)
        assert result.returncode == 0
        assert "[SKIP] RHAISTRAT-2002.md" in result.stdout

    def test_handles_multiple_strategies(self, jira, art_dir):
        jira.create("RHAISTRAT-2010", "Push me", "## Business Need\n\nA.")
        jira.create("RHAISTRAT-2011", "Push me too", "## Business Need\n\nB.")
        jira.create("RHAISTRAT-2012", "Skip me", "")

        strat_dir = art_dir / "artifacts" / "strat-tasks"
        _write_strategy(strat_dir / "RHAISTRAT-2010.md",
                        "RHAISTRAT-2010", "RHAIRFE-110", "Refined",
                        jira_key="RHAISTRAT-2010")
        _write_strategy(strat_dir / "RHAISTRAT-2011.md",
                        "RHAISTRAT-2011", "RHAIRFE-111", "Refined",
                        jira_key="RHAISTRAT-2011")
        _write_strategy(strat_dir / "RHAISTRAT-2012.md",
                        "RHAISTRAT-2012", "RHAIRFE-112", "Draft",
                        jira_key="RHAISTRAT-2012")

        result = _run(jira, strat_dir)
        assert result.returncode == 0, f"stderr: {result.stderr}"
        assert "Pushed 2/" in result.stdout
        assert "1 skipped" in result.stdout

    def test_empty_directory(self, art_dir):
        strat_dir = art_dir / "artifacts" / "strat-tasks"

        env = {
            **os.environ,
            "JIRA_SERVER": "http://localhost:9999",
            "JIRA_USER": "admin",
            "JIRA_TOKEN": "admin",
        }
        result = subprocess.run(
            [sys.executable, SCRIPT, "--artifacts-dir", str(strat_dir)],
            env=env, capture_output=True, text=True, cwd=PROJECT_ROOT,
        )
        assert result.returncode == 0
        assert "No RHAISTRAT files found" in result.stdout

    def test_missing_env_vars_exits_2(self, art_dir):
        strat_dir = art_dir / "artifacts" / "strat-tasks"
        _write_strategy(strat_dir / "RHAISTRAT-2020.md",
                        "RHAISTRAT-2020", "RHAIRFE-120", "Refined",
                        jira_key="RHAISTRAT-2020")

        env = {k: v for k, v in os.environ.items()
               if k not in ("JIRA_SERVER", "JIRA_USER", "JIRA_TOKEN")}
        result = subprocess.run(
            [sys.executable, SCRIPT, "--artifacts-dir", str(strat_dir)],
            env=env, capture_output=True, text=True, cwd=PROJECT_ROOT,
        )
        assert result.returncode == 2

    def test_idempotent_double_push(self, jira, art_dir):
        """Running twice pushes the same content without errors."""
        jira.create("RHAISTRAT-2030", "Idempotent", "## Business Need\n\nCtx.")
        strat_dir = art_dir / "artifacts" / "strat-tasks"
        _write_strategy(strat_dir / "RHAISTRAT-2030.md",
                        "RHAISTRAT-2030", "RHAIRFE-130", "Refined",
                        jira_key="RHAISTRAT-2030")

        result1 = _run(jira, strat_dir)
        assert result1.returncode == 0

        result2 = _run(jira, strat_dir)
        assert result2.returncode == 0
        assert "Pushed 1/" in result2.stdout

    def test_ignores_non_rhaistrat_files(self, art_dir):
        strat_dir = art_dir / "artifacts" / "strat-tasks"
        (strat_dir / "STRAT-001.md").write_text("local only file\n")

        env = {
            **os.environ,
            "JIRA_SERVER": "http://localhost:9999",
            "JIRA_USER": "admin",
            "JIRA_TOKEN": "admin",
        }
        result = subprocess.run(
            [sys.executable, SCRIPT, "--artifacts-dir", str(strat_dir)],
            env=env, capture_output=True, text=True, cwd=PROJECT_ROOT,
        )
        assert result.returncode == 0
        assert "No RHAISTRAT files found" in result.stdout
