"""Smoke tests for HTML rendering in generate-report.py and generate-dashboard.py.

Calls generate_html / generate_dashboard with minimal data and asserts the
output contains expected JS functions, Mermaid syntax, and CSS braces.
Catches regressions where lint auto-fixes break f-string brace escaping.
"""
import importlib.util
import os
import tempfile

SCRIPTS_DIR = os.path.join(os.path.dirname(__file__), "..", "scripts")


def _load_module(filename, modname):
    path = os.path.join(SCRIPTS_DIR, filename)
    spec = importlib.util.spec_from_file_location(modname, path)
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod


report = _load_module("generate-report.py", "generate_report")
dashboard = _load_module("generate-dashboard.py", "generate_dashboard")


def _minimal_task():
    return {
        "meta": {
            "title": "Test strategy",
            "source_rfe": "RHAIRFE-0001",
            "priority": "Major",
            "status": "New",
        },
        "body": "RFE body\n\n## Strategy (AI Generated by Agentic SDLC Pipeline)\n\nStrategy text",
    }


def _minimal_review():
    return {
        "meta": {
            "recommendation": "approve",
            "needs_attention": False,
            "reviewers": {
                "feasibility": "pass",
                "testability": "pass",
                "scope": "pass",
                "architecture": "pass",
            },
            "scores": {
                "feasibility": 2,
                "testability": 2,
                "scope": 2,
                "architecture": 2,
                "total": 8,
            },
        },
        "body": "Review body text",
    }


class TestReportHtmlRendering:
    def _render(self):
        tasks = {"RHAISTRAT-1": _minimal_task()}
        reviews = {"RHAISTRAT-1": _minimal_review()}
        with tempfile.NamedTemporaryFile(suffix=".html", delete=False) as f:
            out = f.name
        try:
            report.generate_html(
                tasks, reviews,
                review_comments={},
                skipped=[],
                pending_review=[],
                config={},
                output_path=out,
            )
            with open(out) as f:
                return f.read()
        finally:
            os.unlink(out)

    def test_js_function_braces(self):
        html = self._render()
        assert "function switchPage(page) {" in html
        assert "function toggleDetail(i) {" in html
        assert "function switchTab(i, tab) {" in html
        assert "function zoomDiagram(factor) {" in html
        assert "function resetDiagram() {" in html

    def test_js_block_braces(self):
        html = self._render()
        assert "if (page === 'pipeline' && !mermaidRendered) {" in html
        assert "isDragging = false; });" in html

    def test_mermaid_diamond_nodes(self):
        html = self._render()
        assert "GATE{{Pipeline label gate" in html
        assert "EG{{" in html
        assert "FG{{" in html
        assert "RG{{" in html
        assert "Q{{" in html

    def test_mermaid_decision_nodes(self):
        html = self._render()
        assert 'PA{"AI Strategy HOW' in html

    def test_mermaid_subgraphs(self):
        html = self._render()
        assert 'subgraph P2["Phase 2: Strategy Refinement"]' in html
        assert 'subgraph SC["strategy-create"]' in html

    def test_css_braces(self):
        html = self._render()
        assert "{ cursor: pointer; }" in html

    def test_mermaid_init_braces(self):
        html = self._render()
        assert "mermaid.initialize({" in html
        assert "flowchart: {" in html

    def test_contains_doctype(self):
        html = self._render()
        assert "<!DOCTYPE html>" in html


class TestDashboardHtmlRendering:
    def _render(self):
        run = {
            "run_id": "2026-08-01_test",
            "total": 1,
            "reviewed": 1,
            "approved": 1,
            "approval_rate": 100,
            "delta_approval": None,
            "strategies": [],
        }
        with tempfile.NamedTemporaryFile(suffix=".html", delete=False) as f:
            out = f.name
        try:
            dashboard.generate_dashboard(
                runs=[run],
                exec_summary="Test summary",
                output_path=out,
            )
            with open(out) as f:
                return f.read()
        finally:
            os.unlink(out)

    def test_contains_doctype(self):
        html = self._render()
        assert "<!DOCTYPE html>" in html

    def test_css_body_rule(self):
        html = self._render()
        assert "body {" in html or "body{" in html

    def test_js_function_braces(self):
        html = self._render()
        assert "function " in html
        brace_count = html.count("function ")
        assert brace_count > 0
        assert "{" in html[html.index("function "):]

    def test_chart_js_config(self):
        html = self._render()
        assert "new Chart(" in html or "Chart(" in html or "chart.js" in html.lower()
